### ISSUE TITLE
Testing the blog I ran into

### ISSUE THREAD

**Issue by clemens-tolboom** [denoland/fresh-wordpress-themes#11]
Some feedback while testing `blog`:

## Port

Docker compose uses port 80 but I already have apache running on that port.
  - WordPress can run on a different port. Can we have that in `.env`?

## Wordpress version

http://localhost/wp-admin/update-core.php?force-check=1 gives
- > An automated WordPress update has failed to complete - [please attempt the update again now](http://localhost/wp-admin/update-core.php)
  - > You have version 5.0.1 installed. Update to 5.0.2

I have no clue yet why I did not get `FROM wordpress:6.0.3-apache` as stated in the `Dockerfile`. Maybe because I have another Wordpress image already?!?

## Missing image

On the home page

> GET http://localhost/wp-content/uploads/2008/06/img_8399.jpg 404 (Not Found)

**Comment by clemens-tolboom** [comment]
## Updating Wordpress

Maybe I missed a section but
- I do have: `Current version: 6.0.3` (pfew)
- it seems due to `Could not create directory.`

> Update WordPress
Downloading update from https://downloads.wordpress.org/release/wordpress-6.1.1-new-bundled.zip…
The authenticity of wordpress-6.1.1-new-bundled.zip could not be verified as no signature was found.
Unpacking the update…
Could not create directory. <=======
Installation failed.

**Comment by clemens-tolboom** [comment]
In wordpress `corporate` I created a new WP page adding a gallery and added it to toplevel menu.

http://localhost:8000/new-page gives

```
An error occured during route handling or page rendering.

TypeError: Cannot read properties of undefined (reading 'href')
    at Object.SinglePage (file:///Users/clemens/Sites/wp/fresh/fresh-wordpress-themes/corporate/routes/[name].tsx:70:41)
    at h (https://esm.sh/v103/preact-render-to-string@5.2.1/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:4:1003)
    at h (https://esm.sh/v103/preact-render-to-string@5.2.1/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:4:1103)
    at h (https://esm.sh/v103/preact-render-to-string@5.2.1/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:4:1103)
    at h (https://esm.sh/v103/preact-render-to-string@5.2.1/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:4:1103)
    at h (https://esm.sh/v103/preact-render-to-string@5.2.1/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:4:1103)
    at m (https://esm.sh/v103/preact-render-to-string@5.2.1/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:3:684)
    at realRender (https://raw.githubusercontent.com/denoland/fresh/b12867a5823a338b318b14f1b6e399e61064dce9/src/server/render.ts:184:16)
    at Object.render (https://raw.githubusercontent.com/denoland/fresh/b12867a5823a338b318b14f1b6e399e61064dce9/src/server/render.ts:202:7)
    at Object.render (https://raw.githubusercontent.com/denoland/fresh/b12867a5823a338b318b14f1b6e399e61064dce9/plugins/twind
```

In VSCode `corporate/routes/[name].tsx` has too much **red** for me to follow.

In the end it was failing the **Featured image** so it was a **content creator** error. But not cool to 'produce' such an error by accident.

**Comment by clemens-tolboom** [comment]
This was my2cents for now.
