### ISSUE TITLE
Module not downloaded yet

### ISSUE THREAD

**Issue by digitaldesigndj** [denoland/fresh-wordpress-themes#12]
I get an error. Everything seems to work, but only for one navigation, then it freezes up. I can restart `deno task start` and do another navigation. Frustrating cause I don't know whats wrong, Fresh doesn't have a build step?

```
✘ [ERROR] [plugin deno] Module not downloaded yet.

An error occurred during route handling or page rendering. Error: Build failed with 1 error:
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11

```

**Comment by kt3k** [comment]
What Deno version do you use? The latest Deno is accidentally incompatible with Fresh (now it's fixed in main branch, but not yet released)

The last version of Deno which was compatible with Fresh was v1.32.1
